<script src="<?= base_url() ?>/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="<?= base_url() ?>/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?= base_url() ?>/bower_components/jquery/dist/jquery.min.js"></script>
<script src="<?= base_url() ?>/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?= base_url() ?>/plugins/iCheck/icheck.min.js"></script>
<script src="<?= base_url() ?>/plugins/sweetalert2/sweetalert2.js"></script>
<!-- <script src="/plugins/select2/js/select2.min.js"></script> -->
<script src="<?= base_url() ?>/plugins/select2/js/select2.full.min.js"></script>
<script src="<?= base_url() ?>/dist/js/adminlte.min.js"></script>